apiVersion: v1
kind: Service
metadata:
  name: vote-canary
  labels:
    app.kubernetes.io/name: vote
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: voting-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: vote
    # Argo Rollouts will add the rollouts-pod-template-hash selector
