apiVersion: v1
kind: Secret
metadata:
  name: newrelic-api-key
  labels:
    app.kubernetes.io/part-of: voting-app
    app.kubernetes.io/component: monitoring
type: Opaque
stringData:
  # Mock New Relic API Key
  # In production, this should be injected via external secrets or sealed secrets
  api-key: "NRAK-XO6GY5NFH2FCVMHXUOC4SIKICUO96Q4Z"
