# QA - Testing newrelic canary analysis
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: vote-rollout
spec:
  replicas: 4
  strategy:
    canary:
      analysis:
        args:
        - name: app-name
          value: vote
        - name: error-threshold
          value: '5'
        - name: latency-threshold
          value: '500'
        - name: apdex-threshold
          value: '0.85'
        - name: nr-api-url
          value: https://opsera-nrmock-labs.agent.opsera.dev
        startingStep: 1
        templates:
        - templateName: newrelic-job-analysis
      steps:
      - setWeight: 10
      - pause:
          duration: 1m
      - setWeight: 30
      - pause:
          duration: 1m
      - setWeight: 60
      - pause:
          duration: 1m
      - setWeight: 100
      trafficRouting:
        nginx:
          annotationPrefix: nginx.ingress.kubernetes.io
          stableIngress: voting-app
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: result-rollout
spec:
  replicas: 3
  strategy:
    canary:
      analysis:
        args:
        - name: app-name
          value: result
        - name: error-threshold
          value: '5'
        - name: latency-threshold
          value: '500'
        - name: apdex-threshold
          value: '0.85'
        - name: nr-api-url
          value: https://opsera-nrmock-labs.agent.opsera.dev
        startingStep: 1
        templates:
        - templateName: newrelic-job-analysis
      steps:
      - setWeight: 10
      - pause:
          duration: 1m
      - setWeight: 30
      - pause:
          duration: 1m
      - setWeight: 60
      - pause:
          duration: 1m
      - setWeight: 100
      trafficRouting:
        nginx:
          annotationPrefix: nginx.ingress.kubernetes.io
          stableIngress: voting-app-result
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2
